eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
      #所有的访问 /api-codes/ 的请求，都会自动转到 INDEX-CODES-SERVICE 去。
    api-b:
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
      #所有的访问 /api-backtest/ 的请求，都会自动转到 TREND-TRADING-BACKTEST-SERVICE 去。
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW