eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 30
  server:
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000

spring:
  application:
    name: eureka-server
