eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 2
  server:
    eviction-interval-timer-in-ms: 500
    response-cache-update-interval-ms: 3000

spring:
  application:
    name: eureka-server
